baseurl: "/"
title: "Anson Miu"
page_load_js: "assets/js/main.js"
params:
  description: Personal blogging theme for Stackbit
  layout_style: overflow
  palette: blue
  header:
    title: "Anson Miu"
    tagline: Developer. Road Trip Enthusiast.
    profile_img: images/avatar.jpg
    background: dark
    has_nav: true
    nav_links:
      - label: About
        url: /
        style: link
      - label: Education
        url: /education/
        style: link
      - label: Work Experience
        url: /work/
        style: link
      - label: Projects
        url: /projects/
        style: link
      - label: Travels
        url: /travels/
        style: link
      # - label: Style Guide
      #   url: /style-guide/
      #   style: link
      # - label: Contact
      #   url: /contact/
      #   style: link
    has_social: true
    social_links:
      # - label: Twitter
      #   url: https://twitter.com/
      #   style: icon
      #   icon_class: fab fa-twitter
      #   new_window: true
      # - label: Instagram
      #   url: https://www.instagram.com/
      #   style: icon
      #   icon_class: fab fa-instagram
      #   new_window: true
      - label: GitHub
        url: https://github.com/ansonmiu2014
        style: icon
        icon_class: fab fa-github
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/in/ansonmiu
        style: icon
        icon_class: fab fa-linkedin
        new_window: true
      - label: Email
        url: mailto:me@ansonmiu.dev
        style: icon
        icon_class: fas fa-envelope
      # - label: DEV
      #   url: https://dev.to/
      #   style: icon
      #   icon_class: fab fa-dev
      #   new_window: true
  footer:
    content: "&copy; All rights reserved."
    links:
      - label: Made with Fresh.
        url: https://github.com/stackbithq/stackbit-theme-fresh
        style: link
        new_window: true
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
